PRAGMA foreign_keys = ON;

CREATE TABLE Movie (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT,
  duration_minutes INTEGER,
  poster_url TEXT
);

CREATE TABLE Cinema (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  location TEXT
);

CREATE TABLE Auditorium (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cinema_id INTEGER,
  name TEXT,
  rows INTEGER,
  cols INTEGER,
  FOREIGN KEY (cinema_id) REFERENCES Cinema(id) ON DELETE CASCADE
);

CREATE TABLE Seat (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  auditorium_id INTEGER,
  row_number INTEGER,
  seat_number INTEGER,
  FOREIGN KEY (auditorium_id) REFERENCES Auditorium(id) ON DELETE CASCADE
);

CREATE TABLE Session (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  movie_id INTEGER,
  auditorium_id INTEGER,
  start_time TIMESTAMP NOT NULL,
  FOREIGN KEY (movie_id) REFERENCES Movie(id) ON DELETE CASCADE,
  FOREIGN KEY (auditorium_id) REFERENCES Auditorium(id) ON DELETE CASCADE
);

CREATE TABLE Booking (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (session_id) REFERENCES Session(id) ON DELETE CASCADE
);

CREATE TABLE BookingSeat (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  booking_id INTEGER,
  seat_id INTEGER,
  FOREIGN KEY (booking_id) REFERENCES Booking(id) ON DELETE CASCADE,
  FOREIGN KEY (seat_id) REFERENCES Seat(id) ON DELETE CASCADE
);